# Generated by Django 2.2 on 2021-05-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_movies', to='soloProjectApp.User'),
        ),
    ]
